#include <array>
#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>

#include <nlohmann/json.hpp>
#include <spdlog/spdlog.h>

#include "api/ChannelManager.h"
#include "api/ControlApi.h"
#include "api/MetricsCollector.h"
#include "auth/AuthCli.h"
#include "auth/AuthDb.h"
#include "auth/AuthService.h"
#include "auth/JwtIssuer.h"
#include "auth/LdapClient.h"
#include "auth/LdapConfigRepo.h"
#include "auth/MasterKey.h"
#include "auth/MasterKeyReset.h"
#include "auth/RbacMiddleware.h"
#include "auth/SmtpConfigRepo.h"
#include "auth/SntpClient.h"
#include "auth/TimeConfig.h"
#include "auth/TimeConfigRepo.h"
#include "auth/TimeSource.h"
#include "core/ChannelInstance.h"
#include "core/Watchdog.h"
#include "events/EventBus.h"
#include "gateway/Gateway.h"
#include "gateway/GatewayManager.h"
#include "gateway/TranscodeGateway.h"
#include "gateway/transcode/FfmpegTranscodePipeline.h"
#include "gateway/transcode/ITranscodePipeline.h"
#include "logging/SqlitePlaybackSink.h"
#include "metrics/ProcessMetrics.h"
#include "metrics/ProfileSampler.h"
#include "mounts/MountManager.h"
#include "mounts/MountdRpcClient.h"
#include "mounts/MountsDb.h"
#include "plugins/PluginManager.h"
#include "preview/PreviewManager.h"
#include "stress/StressConfig.h"
#include "stress/StressService.h"
#include "utils/LegacyMigration.h"
#include "utils/Log.h"
#include "utils/Paths.h"
#include "utils/RuntimeLock.h"
#include "utils/SimdRuntime.h"
#include "utils/SystemdNotifier.h"
#include "utils/Tls.h"
#include "utils/TlsConfig.h"

#include <sodium.h>

using json = nlohmann::json;

static std::atomic<bool> g_running{true};
static void on_signal(int) { g_running.store(false); }

namespace {

// 32-byte CSPRNG token in lowercase hex (64 chars). libsodium is already
// linked for the master-key code path; reuse rather than pulling OpenSSL
// just for this one call site.
std::string generateMetricsTokenHex() {
    std::array<unsigned char, 32> buf{};
    randombytes_buf(buf.data(), buf.size());
    std::ostringstream oss;
    for (auto b : buf)
        oss << std::hex << std::setw(2) << std::setfill('0')
            << static_cast<int>(b);
    return oss.str();
}

// Atomic write of the metrics token state file: tmp → chmod 0600 → rename.
// Empty `token` is valid (means "operator chose to disable auth"); the file
// is written with zero bytes so the next start can distinguish "operator
// chose open mode" (file exists, empty) from "fresh install" (file absent).
bool writeMetricsTokenFile(const std::filesystem::path& target,
                           const std::string&           token) {
    std::error_code ec;
    std::filesystem::create_directories(target.parent_path(), ec);
    if (ec) {
        LOG_ERROR("metrics token: cannot create state dir {}: {}",
                  target.parent_path().string(), ec.message());
        return false;
    }
    const auto tmp = target.string() + ".tmp";
    {
        std::ofstream of(tmp, std::ios::trunc | std::ios::binary);
        if (!of) {
            LOG_ERROR("metrics token: cannot open {} for writing", tmp);
            return false;
        }
        of << token;
        if (!of) {
            LOG_ERROR("metrics token: write to {} failed", tmp);
            std::filesystem::remove(tmp, ec);
            return false;
        }
    }
    std::filesystem::permissions(
        tmp,
        std::filesystem::perms::owner_read | std::filesystem::perms::owner_write,
        std::filesystem::perm_options::replace,
        ec);
    if (ec) {
        LOG_ERROR("metrics token: chmod 0600 on {} failed: {}",
                  tmp, ec.message());
        std::filesystem::remove(tmp, ec);
        return false;
    }
    std::filesystem::rename(tmp, target, ec);
    if (ec) {
        LOG_ERROR("metrics token: rename {}→{} failed: {}",
                  tmp, target.string(), ec.message());
        std::filesystem::remove(tmp, ec);
        return false;
    }
    return true;
}

// Trim a single trailing newline. Tokens generated by the engine contain
// no newline, but an operator who edits the file by hand may add one.
std::string readMetricsTokenFile(const std::filesystem::path& path) {
    std::ifstream f(path, std::ios::binary);
    std::ostringstream oss;
    oss << f.rdbuf();
    std::string s = oss.str();
    while (!s.empty() && (s.back() == '\n' || s.back() == '\r'))
        s.pop_back();
    return s;
}

}  // namespace

int main(int argc, char* argv[]) {
    // fix16: process boot timestamp captured at the very start so it survives
    // across config-load and bootstrap, and is always identical to what we
    // expose via process_start_time_seconds.
    const std::int64_t process_start_unix_sec =
        std::chrono::duration_cast<std::chrono::seconds>(
            std::chrono::system_clock::now().time_since_epoch()).count();

    // fix35 — single CLI parse populates a Paths::Args bundle. Every
    // path the binary touches at startup goes through Paths::resolve()
    // so an operator can pin any of them via flag, env, config, or
    // FHS-aware default. Pre-fix35 the same fields were spread across
    // ad-hoc cfg.value() calls with hard-coded fallbacks.
    namespace scp = liveqx::paths;
    std::string         config_path = "config/default.json";
    bool                config_path_explicit = false;
    scp::Args           path_args;
    std::string         reset_admin_user;
    bool                do_print_bootstrap   = false;
    bool                do_reset_admin       = false;
    bool                do_rotate_master_key = false;
    // fix35 A3.13 — destructive master-key reset. Two flags: the "do it"
    // verb and a separate `--confirm-reset` that operators must add by
    // hand. Without the second flag we print a warning and exit 1 — the
    // gate is intentional, see MasterKeyReset.h for the semantics.
    bool                do_reset_master_key  = false;
    bool                confirm_reset        = false;
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if ((arg == "--config" || arg == "-c") && i + 1 < argc) {
            config_path = argv[++i];
            config_path_explicit = true;
        } else if (arg == "--state-dir" && i + 1 < argc) {
            path_args.state_dir = argv[++i];
        } else if (arg == "--log-dir" && i + 1 < argc) {
            path_args.log_dir = argv[++i];
        } else if (arg == "--plugin-dir" && i + 1 < argc) {
            path_args.plugin_dir = argv[++i];
        } else if (arg == "--ui-dir" && i + 1 < argc) {
            path_args.ui_dir = argv[++i];
        } else if (arg == "--config-dir" && i + 1 < argc) {
            path_args.config_dir = argv[++i];
        } else if (arg == "--channels-dir" && i + 1 < argc) {
            path_args.channels_dir = argv[++i];
        } else if (arg == "--gateways-dir" && i + 1 < argc) {
            path_args.gateways_dir = argv[++i];
        } else if (arg == "--auth-db" && i + 1 < argc) {
            path_args.auth_db = argv[++i];
        } else if (arg == "--master-key-file" && i + 1 < argc) {
            path_args.master_key = argv[++i];
        } else if (arg == "--print-bootstrap-password") {
            do_print_bootstrap = true;
        } else if (arg == "--reset-admin-password" && i + 1 < argc) {
            do_reset_admin   = true;
            reset_admin_user = argv[++i];
        } else if (arg == "--rotate-master-key") {
            do_rotate_master_key = true;
        } else if (arg == "--reset-master-key") {
            do_reset_master_key = true;
        } else if (arg == "--confirm-reset") {
            confirm_reset = true;
        } else if (arg[0] != '-') {
            config_path = arg;
            config_path_explicit = true;
        }
    }

    // fix22 c10/24, c15/24: recovery-CLI ветка. Запускается до полного
    // startup'а — config может отсутствовать (например, на свежей
    // системе перед install.sh), поэтому мы не падаем, если config_path
    // не открывается; Paths::resolve просто не увидит cfg-полей.
    auto try_load_config = [&](const std::string& path) -> json {
        std::ifstream cf(path);
        if (!cf) return json::object();
        try { return json::parse(cf); }
        catch (...) { return json::object(); }
    };

    if (do_print_bootstrap || do_reset_admin || do_rotate_master_key
        || do_reset_master_key) {
        const json recovery_cfg = try_load_config(config_path);
        const auto recovery_paths = scp::Paths::resolve(path_args, recovery_cfg);
        const auto db_path  = recovery_paths.authDb();
        const auto key_path = recovery_paths.masterKey();
        if (do_print_bootstrap)
            return liveqx::auth::printBootstrap(db_path);
        if (do_reset_admin)
            return liveqx::auth::resetAdmin(db_path, reset_admin_user);
        if (do_rotate_master_key)
            return liveqx::auth::rotateMasterKey(db_path, key_path);
        if (do_reset_master_key) {
            // fix35 A3.13 — destructive master-key reset. The CLI is
            // responsible for printing the warning when the operator
            // forgot --confirm-reset; the helper just returns
            // NoConfirmation in that case.
            if (!confirm_reset) {
                std::cerr
                    << "WARNING: --reset-master-key destroys the current master key.\n"
                    << "Encrypted secrets (LDAP/SMTP passwords, jwt_secret) will be wiped.\n"
                    << "A backup of the current key will be saved to "
                    << key_path.string() << ".<unix_timestamp>.bak.\n"
                    << "The LiveQX service must be stopped before running this.\n"
                    << "User accounts and Argon2 password hashes are preserved.\n"
                    << "Re-run with --confirm-reset to proceed.\n";
                return 1;
            }
            const auto report =
                liveqx::auth::resetMasterKey(recovery_paths, true);
            using R = liveqx::auth::ResetResult;
            switch (report.result) {
                case R::Success: {
                    std::cout << "master_key_reset: true\n";
                    std::cout << "key_file: " << key_path.string() << "\n";
                    std::cout << "backup_file: "
                              << (report.backup_path.empty()
                                      ? std::string{"(none)"}
                                      : report.backup_path.string())
                              << "\n";
                    std::cout << "wiped: ";
                    if (report.wiped.empty()) std::cout << "(none)";
                    for (std::size_t i = 0; i < report.wiped.size(); ++i) {
                        if (i) std::cout << ',';
                        std::cout << report.wiped[i];
                    }
                    std::cout << "\n";
                    std::cout.flush();
                    return 0;
                }
                case R::ServiceRunning:
                    std::cerr << "ERROR: " << report.error << "\n";
                    return 2;
                case R::DbOpenFailed:
                    std::cerr << "ERROR: cannot open auth.db: "
                              << report.error << "\n";
                    return 1;
                case R::BackupFailed:
                    std::cerr << "ERROR: backup of current master.key failed: "
                              << report.error << "\n";
                    return 1;
                case R::WipeFailed:
                    std::cerr << "ERROR: cannot wipe encrypted secrets: "
                              << report.error << "\n";
                    return 1;
                case R::GenerateFailed:
                    std::cerr << "ERROR: cannot generate new master.key: "
                              << report.error << "\n";
                    return 1;
                case R::NoConfirmation:
                    // Should be unreachable — we already gated above.
                    std::cerr << "ERROR: internal: NoConfirmation after gate\n";
                    return 1;
            }
            return 1;
        }
    }

    std::ifstream f(config_path);
    if (!f) {
        // Without --config the operator probably just hasn't deployed
        // /etc/liveqx/config.json yet — boot with an empty cfg
        // so the FHS defaults fully take over. With --config the
        // operator demanded a specific file, which we still treat as a
        // hard error so a typo doesn't silently skip the override.
        if (config_path_explicit) {
            std::cerr << "Cannot open config: " << config_path << "\n";
            return 1;
        }
        std::cerr << "Note: " << config_path << " not found, "
                     "running with defaults\n";
    }

    json cfg = json::object();
    if (f) {
        try { cfg = json::parse(f); }
        catch (const json::exception& e) {
            std::cerr << "Config parse error: " << e.what() << "\n";
            return 1;
        }
    }

    const auto paths = scp::Paths::resolve(path_args, cfg);

    // fix35 (A3.12) — single-instance lock. Held for the lifetime of
    // main(); released automatically on process exit (or kernel reaping
    // the fd). Acquired BEFORE Log::init so a second instance doesn't
    // race for a writable rotation handle on the same audit/app log.
    auto runtime_lock = liveqx::util::RuntimeLock::tryAcquire(
        paths.stateDir() / "liveqx.lock");
    if (!runtime_lock.held()) {
        std::cerr << "Another LiveQX instance is running ("
                  << runtime_lock.error() << ")\n"
                  << "  lockfile: " << runtime_lock.path().string() << "\n";
        return 1;
    }

    Log::init(paths.logDir().string(),
              cfg.value("log_level", std::string("info")));
    LOG_INFO("Paths resolved: {}", paths.summary());
    Log::installFFmpegRedirect();
    LOG_INFO("LiveQX starting, config={}", config_path);

    // fix28 — pick AVX2 vs scalar before any render code touches a frame.
    liveqx::simd::initFromConfig(
        cfg.value("simd", std::string("auto")));

    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    Watchdog       watchdog;
    // fix35: channel root resolved through Paths (CLI > ENV > config >
    // default = state_dir/channels). The `channel_root_dir` config key
    // is still recognised for backward compat.
    const std::string channel_root = paths.channelsDir().string();

    // fix7 step 7: one-shot migration of pre-fix7 layouts into per-channel
    // folders. Idempotent: skipped when channels/ is already populated.
    if (!channel_root.empty()) {
        try {
            const auto migrated = LegacyMigration::run(config_path, channel_root);
            if (migrated > 0)
                LOG_INFO("Legacy migration: {} channel(s) moved into {}",
                         migrated, channel_root);
        } catch (const std::exception& e) {
            LOG_ERROR("Legacy migration aborted: {}", e.what());
        }
    }

    ChannelManager manager(&watchdog, channel_root);

    // fix26 c3 — global profiler sampler thread (10ms period).
    // Must outlive manager so unregisterChannel is never called on a dead object.
    liveqx::profiler::ProfileSampler profile_sampler;
    manager.setProfileSampler(&profile_sampler);

    // fix8: process-wide owner of all per-channel proof-of-play SQLite files.
    // Channels with playback_log.sink == "db" share this sink; "file" /
    // "none" channels keep their own sink and ignore this injection.
    const int default_retention_days =
        cfg.value("playback_log_default_retention_days", 90);
    liveqx::logging::SqlitePlaybackSink playback_sink(default_retention_days);
    manager.setSqlitePlaybackSink(&playback_sink);

    // fix7: every channel lives on disk under channel_root. Pre-fix7 configs
    // are auto-migrated above (LegacyMigration::run) so by this point the
    // global config has no `channels: [...]` array — there is nothing else
    // to consult.
    const std::size_t loaded = manager.loadFromRoot();
    if (loaded > 0) {
        LOG_INFO("Bootstrapped {} channel(s) from {}", loaded, channel_root);
        // fix17: skip auto-play for channels that were paused at last save.
        // Persisting the operator's stop intent across restarts is the whole
        // point of state.db — auto-playing them would silently undo it. We
        // collect (id, paused) under the iterate lock and play() outside.
        struct BootEntry { int id; bool paused; };
        std::vector<BootEntry> entries;
        manager.forEachChannel([&entries](const ChannelInstance& ch) {
            BootEntry be;
            be.id     = ch.id();
            be.paused = ch.wasPausedAtLastSave();
            entries.push_back(be);
        });
        for (const auto& e : entries) {
            if (e.paused) {
                LOG_INFO("Channel {} stays stopped (paused=true in state.db)",
                         e.id);
                continue;
            }
            const auto r = manager.play(e.id);
            if (r != ChannelManager::Result::Ok)
                LOG_ERROR("Failed to start channel {}: {}", e.id,
                          channelManagerResultName(r));
        }
    }
    // fix17: every per-channel state.db has been opened by build() and any
    // cursor/paused state has been consumed by the loop above. Flip readiness
    // so /readyz reports state_persistence_loaded=true and Kubernetes shifts
    // traffic to this pod.
    manager.setStatePersistenceLoaded(true);

    if (manager.size() == 0) {
        // fix7: an empty start is a legitimate state — the operator can
        // POST /api/channels later. We just keep the API up.
        LOG_WARN("No channels on disk — waiting for POST /api/channels");
    }

    // fix18: packet-level UDP/multicast forwarders live in their own root.
    // fix35: resolved through Paths (default = state_dir/gateways).
    // fix40 A6 step 9: register the FFmpeg-backed transcode pipeline factory
    // so newly-constructed Transcode-mode gateways automatically attach a
    // decode→encode pipeline. Tests that don't link FFmpeg leave this
    // registration absent and the gateway runs in pass-through.
    liveqx::gateway::TranscodeGateway::registerPipelineFactory(
        [](const liveqx::gateway::TranscodeCfg& tc)
            -> std::unique_ptr<liveqx::gateway::transcode::ITranscodePipeline> {
            return std::make_unique<
                liveqx::gateway::transcode::FfmpegTranscodePipeline>(tc);
        });
    const std::string gateway_root = paths.gatewaysDir().string();
    liveqx::gateway::GatewayManager gateways(gateway_root);
    if (!gateway_root.empty()) {
        const auto gw_loaded = gateways.loadFromRoot();
        if (gw_loaded > 0)
            LOG_INFO("Bootstrapped {} gateway(s) from {}",
                     gw_loaded, gateway_root);
    }

    watchdog.start();

    {
        const int api_port = cfg.value("api_port", 8080);

        // fix16: process-wide /proc reader + Prometheus exporter. ProcessMetrics
        // caches /proc/self snapshots (1s TTL); MetricsCollector is stateless
        // and walks ChannelManager + ProcessMetrics on each scrape.
        ProcessMetrics process_metrics(process_start_unix_sec);
        BuildInfo build_info{
            LIVEQX_VERSION,
            LIVEQX_COMMIT,
            LIVEQX_BUILD_TIME,
            LIVEQX_BUILD_TYPE
        };
        // MetricsCollector is built later, after EventBus + StressService so
        // it can include stress_* families in /api/metrics.

        // fix16: liveness threshold is operator-tunable. 10 s ≈ 250 missed
        // ticks at 25fps; raise on slow-disk benches, lower for k8s probes
        // that want pages within a frame budget.
        //
        // The metrics bearer token now lives in a state-dir file owned by
        // the engine, not in /etc/liveqx/config.json. Shipped templates
        // therefore never carry a real secret, and revoke/regenerate via
        // the UI no longer requires write access to /etc/. Three-state
        // semantics of the file:
        //   * absent           → first start, generate + persist
        //   * present, content → that string is the active token
        //   * present, empty   → operator explicitly disabled auth
        LivezOptions livez_opts;
        if (cfg.contains("livez") && cfg["livez"].is_object()) {
            livez_opts.stuck_threshold_seconds =
                cfg["livez"].value("stuck_threshold_seconds", 10.0);
        }
        const auto metrics_token_path = paths.metricsBearerTokenFile();
        if (std::filesystem::exists(metrics_token_path)) {
            livez_opts.metrics_bearer_token =
                readMetricsTokenFile(metrics_token_path);
        } else {
            // One-shot migration: existing installs may have the legacy
            // `livez.metrics_bearer_token` in config.json. Honour it on
            // first boot of the new binary so Prometheus scrapers keep
            // working, then write it to the new location and let the
            // config field become inert.
            std::string seed;
            if (cfg.contains("livez") && cfg["livez"].is_object()
                && cfg["livez"].contains("metrics_bearer_token")
                && cfg["livez"]["metrics_bearer_token"].is_string()) {
                seed = cfg["livez"]["metrics_bearer_token"].get<std::string>();
            }
            if (seed.empty()) {
                seed = generateMetricsTokenHex();
                LOG_INFO("metrics token: generated fresh ({}…), persisting to {}",
                         seed.substr(0, 8), metrics_token_path.string());
            } else {
                LOG_INFO("metrics token: migrated from config.json to {}",
                         metrics_token_path.string());
            }
            if (!writeMetricsTokenFile(metrics_token_path, seed)) {
                LOG_ERROR("metrics token: bootstrap write failed; /api/metrics will be "
                          "unauthenticated until the next successful write");
            } else {
                livez_opts.metrics_bearer_token = seed;
            }
        }
        livez_opts.on_metrics_token_changed =
            [metrics_token_path](const std::string& new_token) -> bool {
                if (!writeMetricsTokenFile(metrics_token_path, new_token))
                    return false;
                if (new_token.empty())
                    LOG_INFO("metrics token: cleared (auth disabled)");
                else
                    LOG_INFO("metrics token: updated ({}…)",
                             new_token.substr(0, 8));
                return true;
            };

        // ── fix22 c24/24 — Auth + RBAC wiring ──────────────────────────
        //
        // Этот блок собирает все auth-объекты в стек: AuthDb → MasterKey →
        // JwtIssuer (с persisted secret) → AuthService → LdapConfigRepo /
        // SmtpConfigRepo / RbacMiddleware. ControlApi получает их сырыми
        // указателями и регистрирует RBAC-правила на старте. После
        // bootstrap'а initial admin'а manager.setAuthLoaded(true) флипает
        // /readyz в зелёный.
        namespace sa = liveqx::auth;
        const std::string auth_db_path    = paths.authDb().string();
        const std::string master_key_path = paths.masterKey().string();

        sa::AuthDb auth_db(auth_db_path);
        if (!auth_db.open()) {
            LOG_ERROR("Cannot open auth.db at {}", auth_db_path);
            return 1;
        }
        sa::MasterKey master_key(master_key_path);
        if (!master_key.load()) {
            LOG_ERROR("Cannot load master key from {}", master_key_path);
            return 1;
        }

        // JWT signing secret: либо берём расшифрованный из БД, либо
        // generates 32 random hex bytes (64-char string ≥256 bit) и
        // запоминаем в jwt_secret под master key'ом. Rotation — через
        // recovery-CLI --rotate-master-key.
        std::string jwt_secret;
        if (auto blob = auth_db.readJwtSecret(); blob.has_value()) {
            auto dec = master_key.decrypt(*blob);
            if (!dec) {
                LOG_ERROR("Cannot decrypt jwt_secret with master key — wrong key?");
                return 1;
            }
            jwt_secret = std::move(*dec);
        } else {
            std::array<std::uint8_t, 32> rb{};
            randombytes_buf(rb.data(), rb.size());
            char hex[65];
            for (std::size_t i = 0; i < rb.size(); ++i)
                std::snprintf(hex + 2 * i, 3, "%02x", rb[i]);
            hex[64] = 0;
            jwt_secret.assign(hex, 64);
            const auto now_sec =
                std::chrono::duration_cast<std::chrono::seconds>(
                    std::chrono::system_clock::now().time_since_epoch())
                    .count();
            if (!auth_db.storeJwtSecret(master_key.encrypt(jwt_secret), now_sec)) {
                LOG_ERROR("Cannot persist freshly-generated jwt_secret");
                return 1;
            }
            LOG_INFO("Generated fresh jwt_secret and stored in auth.db");
        }

        sa::JwtIssuer        jwt(jwt_secret);
        sa::LdapConfigRepo   ldap_repo(auth_db, master_key);
        sa::SmtpConfigRepo   smtp_repo(auth_db, master_key);
        sa::TimeConfigRepo   time_repo(auth_db);
        sa::TimeSourceManager time_src;
        auto                 sntp_client = std::make_shared<sa::SntpClient>();
        time_src.setNtpDependencies(
            sntp_client,
            [&time_repo](std::int64_t off_ms, std::int64_t at_unix_sec) {
                time_repo.updateNtpSyncResult(off_ms, at_unix_sec);
            });
        // Loaded TimeConfig | дефолт SystemLocal/UTC. reconfigure() сразу
        // запускает NtpSource'а если source=Ntp.
        {
            sa::TimeConfig boot_cfg;
            if (auto cur = time_repo.load(); cur.has_value())
                boot_cfg = std::move(*cur);
            time_src.reconfigure(boot_cfg);
        }

        // fix33 C — серверная TZ-провайдер для inherit-каналов.
        // ChannelInstance дёргает этот колл-бэк, когда channel_timezone null/absent;
        // ControlApi /api/system/time PUT после сохранения вызывает
        // manager.notifyServerTimezoneChanged(), обходящий все inherit-каналы.
        manager.setServerTimezoneGetter([&time_repo]() -> std::string {
            if (auto cur = time_repo.load(); cur.has_value() &&
                !cur->server_timezone.empty()) {
                return cur->server_timezone;
            }
            return "UTC";
        });

        // Locale-user grants resolver: читает channel_permissions по uid.
        sa::AuthService auth_svc(auth_db, jwt,
            [&auth_db](std::int64_t uid) {
                std::vector<sa::ChannelGrant> out;
                for (const auto& row :
                     auth_db.listChannelPermissionsForUser(uid)) {
                    sa::ChannelGrant g;
                    g.channel_id = row.channel_id;
                    g.permission = row.permission;
                    out.push_back(g);
                }
                return out;
            });

        // LDAP authenticator: lambda поверх LdapConfigRepo + LdapClient.
        // Каждый login() создаёт новый LdapClient (cheap relative to RTT).
        // Отключённый LDAP — Disabled, AuthService уйдёт в Local-only.
        auth_svc.setLdapAuthenticator(
            [&ldap_repo](std::string_view user, std::string_view pass) {
                sa::AuthService::LdapLoginContext lctx;
                auto lcfg = ldap_repo.load();
                if (!lcfg.has_value() || !lcfg->enabled) {
                    lctx.reason = sa::AuthService::LdapReason::Disabled;
                    return lctx;
                }
                sa::LdapClient cli(*lcfg);
                auto r = cli.authenticate(user, pass);
                lctx.email  = r.email;
                lctx.groups = r.groups;
                if (!r.ok) {
                    using Rsn = sa::LdapClient::AuthResult::Reason;
                    using Out = sa::AuthService::LdapReason;
                    switch (r.reason) {
                        case Rsn::ConnectionFailed:   lctx.reason = Out::ConnectionFailed;   break;
                        case Rsn::BindServiceFailed:  lctx.reason = Out::BindServiceFailed;  break;
                        case Rsn::UserNotFound:       lctx.reason = Out::UserNotFound;       break;
                        case Rsn::InvalidCredentials: lctx.reason = Out::InvalidCredentials; break;
                        case Rsn::ConfigError:        lctx.reason = Out::ConfigError;        break;
                        default:                      lctx.reason = Out::Other;              break;
                    }
                    lctx.error = r.error;
                    return lctx;
                }
                auto role = sa::AuthService::pickRoleForGroups(
                    r.groups, lcfg->group_role_map);
                if (!role) {
                    lctx.reason = sa::AuthService::LdapReason::NoRoleMapped;
                    return lctx;
                }
                lctx.ok   = true;
                lctx.role = *role;
                std::vector<sa::AuthService::ChannelAclEntry> acls;
                acls.reserve(lcfg->channel_acl.size());
                for (const auto& a : lcfg->channel_acl) {
                    sa::AuthService::ChannelAclEntry e;
                    e.channel_id  = a.channel_id;
                    e.group_perms = a.group_perms;
                    acls.push_back(std::move(e));
                }
                lctx.channel_grants =
                    sa::AuthService::pickAclGrantsForGroups(r.groups, acls);
                lctx.reason = sa::AuthService::LdapReason::Ok;
                return lctx;
            });

        // LDAP grants resolver на refresh — пересчитывает per-channel
        // grants по cached groups, не требует nового LDAP-bind'а.
        auth_svc.setLdapGrantsResolver(
            [&ldap_repo](const std::vector<std::string>& groups) {
                std::vector<sa::ChannelGrant> empty;
                auto lcfg = ldap_repo.load();
                if (!lcfg.has_value()) return empty;
                std::vector<sa::AuthService::ChannelAclEntry> acls;
                acls.reserve(lcfg->channel_acl.size());
                for (const auto& a : lcfg->channel_acl) {
                    sa::AuthService::ChannelAclEntry e;
                    e.channel_id  = a.channel_id;
                    e.group_perms = a.group_perms;
                    acls.push_back(std::move(e));
                }
                return sa::AuthService::pickAclGrantsForGroups(groups, acls);
            });

        sa::RbacMiddleware rbac(auth_db, jwt);

        // fix35 (A3.16) — wire the initial-admin password file path so
        // bootstrapInitialAdmin can write the plaintext into state/ and
        // changeOwnPassword can auto-delete it on first password change.
        auth_svc.setInitialAdminPasswordFile(paths.initialAdminPasswordFile());

        // Idempotent admin bootstrap. The plaintext is dropped into
        // <state_dir>/initial_admin_password.txt (mode 0600) by
        // bootstrapInitialAdmin when password_file_path is wired. Only
        // when the file write fails do we fall back to logging the
        // password — otherwise the LOG_WARN below is silent on plaintext.
        if (auto br = auth_svc.bootstrapInitialAdmin(); br.created) {
            if (br.password_file_path.empty()) {
                // File-write path unavailable (no setter wired) — single
                // logged copy is the only way the operator gets the
                // password. Pre-fix35 behaviour, retained as a fallback.
                LOG_WARN("Bootstrap admin '{}' created — TEMP_PASSWORD='{}' "
                         "(change at first login)",
                         br.username, br.plaintext_password);
            } else {
                LOG_WARN("Bootstrap admin '{}' created — password is in {}",
                         br.username, br.password_file_path.string());
            }
        }

        manager.setAuthLoaded(true);

        // fix23 — process-wide event bus for SSE fan-out and per-channel
        // WebRTC preview registry. Both are passed down to ControlApi
        // (REST surface) and event_bus is wired into ChannelManager so
        // every existing + future ChannelInstance publishes lifecycle
        // events. PreviewManager defaults can be tuned via the optional
        // "preview" object in the global config.
        liveqx::events::EventBus event_bus;
        manager.setEventBus(&event_bus);
        gateways.setEventBus(&event_bus);
        auth_svc.setEventBus(&event_bus);

        // ── fix41 — CIFS/NFS mounts ─────────────────────────────────────
        //
        // liveqx is the source-of-truth for mount config — UI
        // writes here, reconcile-on-boot reapplies via the privileged
        // liveqx-mountd helper over AF_UNIX. Opening mounts.db
        // unconditionally (table is empty on first boot). reconcileOnBoot
        // is best-effort: if mountd isn't up yet, helper RPCs fail with
        // "rpc_connect_failed" and the periodic sync thread retries.
        namespace mns = liveqx::mounts;
        mns::MountsDb mounts_db(paths.mountsDb());
        if (!mounts_db.open()) {
            LOG_ERROR("Cannot open mounts.db at {}", paths.mountsDb().string());
            return 1;
        }
        mns::MountdRpcClient::Config mountd_rpc_cfg;
        if (cfg.contains("mounts") && cfg["mounts"].is_object()) {
            const auto& mc = cfg["mounts"];
            if (mc.contains("socket_path") && mc["socket_path"].is_string())
                mountd_rpc_cfg.socket_path =
                    mc["socket_path"].get<std::string>();
        }
        auto mountd_rpc =
            std::make_shared<mns::MountdRpcClient>(mountd_rpc_cfg);
        mns::MountManager mounts_mgr(mounts_db, master_key, mountd_rpc);
        LOG_INFO("Mounts: db={} mountd_socket={} ({} row/s)",
                 paths.mountsDb().string(),
                 mountd_rpc_cfg.socket_path.string(),
                 mounts_mgr.size());
        mounts_mgr.reconcileOnBoot();

        // Background pull of helper status. 30s cadence — same as the
        // helper's own watchdog touch; faster polling just thrashes
        // sqlite. jthread destructor request_stop+join's on scope exit.
        std::jthread mounts_status_thread(
            [&mounts_mgr](std::stop_token st) {
                // Small initial delay so reconcileOnBoot's apply settles
                // in mountd before we re-read its status table.
                for (int i = 0; i < 5 && !st.stop_requested(); ++i)
                    std::this_thread::sleep_for(std::chrono::seconds(1));
                while (!st.stop_requested()) {
                    mounts_mgr.syncStatusFromHelper();
                    for (int i = 0; i < 30 && !st.stop_requested(); ++i)
                        std::this_thread::sleep_for(std::chrono::seconds(1));
                }
            });

        // ── fix26 c13/14 — Stress runner + scheduler ────────────────────
        //
        // Bootstrap order: persisted state (stress_state_path) wins over
        // the cfg["stress"] block, which wins over StressConfig defaults.
        // The persist callback writes back to stress_state_path on every
        // successful PUT /api/stress/config so the operator's last edit
        // survives restart.
        // fix35: stress.json sits under state_dir; Paths derives the
        // exact location. Pre-fix35 cfg key `stress_state_path` is
        // honoured at the Paths level via state_dir override.
        const std::filesystem::path stress_state_path =
            cfg.value("stress_state_path", paths.stressJson().string());
        liveqx::stress::StressConfig stress_initial;
        {
            namespace ssns = liveqx::stress;
            std::error_code ec;
            if (std::filesystem::exists(stress_state_path, ec)) {
                std::ifstream sf(stress_state_path);
                if (sf) {
                    try {
                        stress_initial = ssns::StressConfig::fromJson(json::parse(sf));
                        LOG_INFO("Stress: loaded persisted config from {}",
                                 stress_state_path.string());
                    } catch (const std::exception& e) {
                        LOG_WARN("Stress: cannot parse {} ({}); falling back to cfg",
                                 stress_state_path.string(), e.what());
                    }
                }
            } else if (cfg.contains("stress") && cfg["stress"].is_object()) {
                stress_initial = ssns::StressConfig::fromJson(cfg["stress"]);
            }
        }
        liveqx::stress::StressService stress_service(
            manager, stress_initial, /*builder=*/{}, &event_bus);
        stress_service.setPersistCallback(
            [stress_state_path](const liveqx::stress::StressConfig& c) {
                std::error_code ec;
                std::filesystem::create_directories(
                    stress_state_path.parent_path(), ec);
                const auto tmp = stress_state_path.string() + ".tmp";
                {
                    std::ofstream of(tmp, std::ios::trunc);
                    if (!of) {
                        LOG_ERROR("Stress: cannot open {} for write", tmp);
                        return;
                    }
                    of << c.toJson().dump(2);
                }
                std::filesystem::rename(tmp, stress_state_path, ec);
                if (ec)
                    LOG_ERROR("Stress: rename {}→{} failed: {}",
                              tmp, stress_state_path.string(), ec.message());
            });

        // fix19 c3: PluginManager owns the on-disk plugin tree (sibling of
        // channels/). scanAndLoad() is non-fatal — broken plugins surface
        // through /api/plugins as gone, the channel manager keeps booting.
        // Audit hook is wired in commit 5/15 once the AuthService surface
        // is settled.
        //
        // Constructed *before* MetricsCollector so /api/version can include
        // each loaded plugin's attribution text (fix19 c10).
        const std::string plugins_root_dir       = paths.pluginDir().string();
        const std::string plugins_allow_list_dir =
            paths.pluginsAllowListDir().string();
        liveqx::plugins::PluginManager plugins_mgr(
            plugins_root_dir, spdlog::default_logger());
        if (!plugins_allow_list_dir.empty())
            plugins_mgr.setAllowListDir(plugins_allow_list_dir);
        const auto plugins_loaded = plugins_mgr.scanAndLoad();
        LOG_INFO("Plugins: {} loaded from {} (allow-list={})",
                 plugins_loaded, plugins_root_dir,
                 plugins_allow_list_dir.empty()
                   ? "<disabled>" : plugins_allow_list_dir);

        MetricsCollector metrics(manager, process_metrics, build_info,
                                 &gateways, &stress_service, &plugins_mgr,
                                 &mounts_mgr);

        liveqx::preview::PreviewManager::Config preview_cfg;
        if (cfg.contains("preview") && cfg["preview"].is_object()) {
            const auto& pcfg = cfg["preview"];
            preview_cfg.max_clients_per_channel =
                pcfg.value("max_clients_per_channel",
                           preview_cfg.max_clients_per_channel);
            preview_cfg.max_active_channels =
                pcfg.value("max_active_channels",
                           preview_cfg.max_active_channels);
            preview_cfg.idle_shutdown_sec =
                pcfg.value("idle_shutdown_sec",
                           preview_cfg.idle_shutdown_sec);
            if (pcfg.contains("ice_servers") && pcfg["ice_servers"].is_array()) {
                preview_cfg.default_ice_servers.clear();
                for (const auto& s : pcfg["ice_servers"])
                    if (s.is_string())
                        preview_cfg.default_ice_servers.push_back(
                            s.get<std::string>());
            }
        }
        liveqx::preview::PreviewManager preview(preview_cfg);
        // fix34 D2.8 — wire the manager into every existing + future
        // ChannelInstance so the render loop's tap fans frames into preview
        // sessions. Detached on shutdown (see manager.setPreviewManager
        // below) so a late publish doesn't touch a destroyed manager.
        manager.setPreviewManager(&preview);

        // fix38 — TLS bootstrap. Schema is parsed once here; the binary
        // resolves cert/key paths according to mode and fans them into
        // ControlApi via TlsBindings. Failures are fatal: an operator who
        // explicitly opts into provided/auto deserves a hard error rather
        // than a silent fallback to plain HTTP.
        //
        // The bootstrap runs both at boot and on every TLS hot-reload
        // (commit 6/8) so cert files newly written by /api/tls/import or
        // /api/tls/regenerate-server are picked up by the next listener
        // incarnation. tls_failed signals the lambda's caller to abort.
        namespace sct = liveqx::tls;
        const std::string api_bind = cfg.value("api_bind", std::string{"0.0.0.0"});
        bool tls_failed = false;
        auto buildTlsBindings = [&]() -> TlsBindings {
            TlsBindings out;
            out.bind = api_bind;
            auto pr = sct::parseConfig(cfg);
            for (const auto& w : pr.warnings) LOG_WARN("tls config: {}", w);
            if (!pr.ok()) {
                for (const auto& e : pr.errors) LOG_ERROR("tls config: {}", e);
                tls_failed = true;
                return out;
            }
            const auto& tcfg     = pr.config;
            const auto  tls_dir  = paths.tlsDir();
            out.mode      = sct::modeToString(tcfg.mode);
            out.san_extra = tcfg.san_extra;

            switch (tcfg.mode) {
            case sct::Mode::Auto: {
                std::error_code ec;
                std::filesystem::create_directories(tls_dir, ec);
                if (ec) {
                    LOG_ERROR("tls: cannot create {}: {}",
                              tls_dir.string(), ec.message());
                    tls_failed = true; return out;
                }
                auto ca = sct::ensureCa(tls_dir);
                if (!ca.ok()) {
                    LOG_ERROR("tls: ensureCa failed: {}", ca.error);
                    tls_failed = true; return out;
                }
                if (ca.generated) {
                    LOG_INFO("tls: generated internal CA at {}",
                             ca.cert_path.string());
                } else {
                    LOG_INFO("tls: reusing internal CA at {}",
                             ca.cert_path.string());
                }

                // Re-mint server.crt every boot when missing, expired,
                // or older than 30 days. Cheap (~5ms) and keeps SAN
                // drift in sync with NIC/DNS changes.
                const auto srv_cert_path = tls_dir / "server.crt";
                bool need_reissue = !std::filesystem::exists(
                    srv_cert_path, ec);
                if (!need_reissue) {
                    auto ci = sct::readCertInfo(srv_cert_path);
                    if (ci.subject.empty() || ci.days_remaining < 30) {
                        need_reissue = true;
                    }
                }
                std::filesystem::path srv_cert, srv_key;
                if (need_reissue) {
                    auto sans = sct::autoDetectSans(tcfg.san_extra);
                    if (sans.empty()) {
                        LOG_ERROR("tls: auto-detected SAN list is empty; "
                                  "cannot issue server cert");
                        tls_failed = true; return out;
                    }
                    auto srv = sct::issueServerCert(tls_dir,
                                                    "liveqx", sans);
                    if (!srv.ok()) {
                        LOG_ERROR("tls: issueServerCert failed: {}", srv.error);
                        tls_failed = true; return out;
                    }
                    srv_cert = srv.cert_path;
                    srv_key  = srv.key_path;
                    LOG_INFO("tls: issued server cert sans_dns={} sans_ip4={} "
                             "sans_ip6={}", sans.dns_names.size(),
                             sans.ip_v4.size(), sans.ip_v6.size());
                } else {
                    srv_cert = srv_cert_path;
                    srv_key  = tls_dir / "server.key";
                    LOG_INFO("tls: reusing server cert at {}",
                             srv_cert.string());
                }
                out.cert_path = srv_cert;
                out.key_path  = srv_key;
                out.tls_dir   = tls_dir;
                break;
            }
            case sct::Mode::Provided: {
                auto vk = sct::verifyKeyPair(tcfg.cert_path, tcfg.key_path);
                if (!vk.ok) {
                    LOG_ERROR("tls: provided cert+key invalid: {}", vk.error);
                    tls_failed = true; return out;
                }
                out.cert_path = tcfg.cert_path;
                out.key_path  = tcfg.key_path;
                out.tls_dir   = tls_dir;  // /api/tls/* still usable
                LOG_INFO("tls: serving operator-provided cert {}",
                         tcfg.cert_path.string());
                break;
            }
            case sct::Mode::BehindProxy: {
                if (tcfg.trust_proxy_cidrs.empty()) {
                    LOG_WARN("tls: behind_proxy mode without "
                             "trust_proxy_cidrs — X-Forwarded-* will not be "
                             "honoured (safe default)");
                } else {
                    LOG_WARN("tls: behind_proxy mode — trust_proxy_cidrs "
                             "configured ({} entry/ies) but enforcement is "
                             "deferred to a follow-up commit; treating "
                             "every X-Forwarded-* as untrusted",
                             tcfg.trust_proxy_cidrs.size());
                }
                LOG_INFO("tls: serving plain HTTP (TLS terminates upstream)");
                break;
            }
            case sct::Mode::Disabled: {
                if (api_bind != "127.0.0.1" && api_bind != "::1" &&
                    api_bind != "localhost" &&
                    !tcfg.allow_insecure_bind) {
                    LOG_ERROR("tls.mode=disabled with non-loopback bind={} "
                              "and allow_insecure_bind=false. Either set "
                              "api_bind=127.0.0.1 or "
                              "tls.allow_insecure_bind=true to opt-in.",
                              api_bind);
                    tls_failed = true; return out;
                }
                LOG_WARN("tls: disabled — Control API serving plain HTTP. "
                         "Use only on a trusted network or for local dev.");
                break;
            }
            }
            return out;
        };

        TlsBindings tls_bindings = buildTlsBindings();
        if (tls_failed) return 1;

        // fix21 — sd_notify(READY=1) lands here: REST is up, channels are
        // bootstrapped, gateways loaded. Outside systemd this is a no-op.
        liveqx::sysd::SystemdNotifier notifier;
        notifier.ready("started, channels=" + std::to_string(manager.size()));

        // fix21 — periodic STATUS+WATCHDOG keep-alive. Cadence comes from
        // $WATCHDOG_USEC (set by systemd from WatchdogSec=); outside systemd
        // SystemdNotifier::enabled() is false and startWatchdogLoop() is a
        // no-op. The provider walks ChannelManager under shared_lock — cheap.
        notifier.startWatchdogLoop([&manager] {
            return ChannelManager::formatStatusLine(manager.snapshotForStatus());
        });

        // fix38 — TLS hot-reload loop. /api/tls/regenerate-server and
        // /api/tls/import set tls_reload_pending and clear g_running so
        // the wait-for-shutdown loop falls through. We then stop() the
        // listener (joins handler threads cleanly), re-run buildTlsBindings
        // (which reads the just-written cert files from disk), and spin
        // up a fresh ControlApi over the same shared dependencies. Every
        // iteration after the first re-arms g_running because SIGINT/
        // SIGTERM use the same flag for actual shutdown.
        std::atomic<bool> tls_reload_pending{false};
        do {
            ControlApi api(api_port, manager, &metrics, livez_opts, &gateways,
                           &auth_svc, &ldap_repo, &smtp_repo, &rbac,
                           &event_bus, &preview, &stress_service, &plugins_mgr,
                           &master_key, &mounts_mgr, tls_bindings,
                           &time_repo, &time_src, sntp_client.get());
            api.setOnTlsReload([&]() {
                tls_reload_pending.store(true, std::memory_order_release);
                g_running.store(false, std::memory_order_release);
            });
            // fix35 A3.5–A3.9 — mount static UI (or 503-stub if headless).
            api.mountUi(paths.uiDir());
            api.start();
            const bool tls_on = !tls_bindings.cert_path.empty() &&
                                !tls_bindings.key_path.empty();
            LOG_INFO("Control API on {}://{}:{}/api/channels",
                     tls_on ? "https" : "http", api_bind, api_port);

            LOG_INFO("Running — send SIGINT or SIGTERM to stop");
            while (g_running.load(std::memory_order_relaxed))
                std::this_thread::sleep_for(std::chrono::milliseconds(100));

            api.stop();

            if (tls_reload_pending.exchange(false, std::memory_order_acq_rel)) {
                LOG_INFO("TLS reload — rebuilding listener with rotated cert");
                tls_bindings = buildTlsBindings();
                if (tls_failed) {
                    LOG_ERROR("TLS reload bootstrap failed; staying down");
                    break;
                }
                g_running.store(true, std::memory_order_release);
                continue;
            }
            break;
        } while (true);

        LOG_INFO("Shutting down…");
        notifier.stopWatchdogLoop();
        notifier.stopping("draining");
        // event_bus + preview die at scope-exit. Unhook the bus + preview
        // from the manager first so no late publish or render-tap racing
        // past stopAll() touches a dead bus / manager.
        manager.setEventBus(nullptr);
        manager.setPreviewManager(nullptr);
        auth_svc.setEventBus(nullptr);
    }

    gateways.stopAll();
    watchdog.stop();
    manager.stopAll();
    LOG_INFO("Done");
    spdlog::shutdown();
    return 0;
}
